FROM docker.io/library/archlinux:latest

# 1
ENV TERM=xterm-256color
COPY files/ /opt/9318/

# 2
USER root
WORKDIR /root
ENV USER=root
ENV HOME=/root
RUN /opt/9318/docker.install.root.sh

# 3
USER runner
WORKDIR /home/runner
ENV USER=runner
ENV HOME=/home/runner
RUN /opt/9318/docker.install.runner.sh

# 4 
RUN sudo rm -rf /opt/9318/
